# Makefile for luci-app-acctl
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI - AC Controller
LUCI_DEPENDS:=+luci-base +luci-lib-base +libuci-lua +luci-compat +acctl
LUCI_PKGARCH:=all

include ../../luci.mk
