# Makefile for luci-app-acctl
# LuCI Application Package

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI - AC Controller
LUCI_DEPENDS:=+luci-base +luci-lib-base +libuci-lua +luci-compat
LUCI_PKGARCH:=all

include ../../luci.mk
