include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-acctl
PKG_VERSION:=2.0
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/luci-app-acctl
  SECTION:=luci
  CATEGORY:=LuCI
  SUBMENU:=Access Controllers
  TITLE:=LuCI App - AC Controller
  DEPENDS:=+acctl-ac +libuci-lua +libubus-lua
  URL:=https://github.com/bhrq12/acctl
  MAINTAINER:=jianxi sun <ycsunjane@gmail.com>
  PKGARCH:=all
endef

define Package/luci-app-acctl/description
  LuCI Web Interface for AC Controller
  Compatible with OpenWrt 18.06+ (Lua) and OpenWrt 22+ (ucode)
  Requires: acctl-ac
endef

define Build/Prepare
	$(CP) ./luci  $(PKG_BUILD_DIR)/luci
	$(CP) ./luci24 $(PKG_BUILD_DIR)/luci24
endef

define Build/Configure
endef

define Build/Compile
	# No compilation needed for LuCI app
endef

define Package/luci-app-acctl/install
	# Install LuCI files for OpenWrt 18.06-21.02 (Lua)
	$(INSTALL_DIR) $(1)/usr/lib/lua/luci/controller
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/luasrc/controller/acctl.lua \
		$(1)/usr/lib/lua/luci/controller/acctl.lua

	$(INSTALL_DIR) $(1)/usr/lib/lua/luci/model/cbi/acctl
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/model/cbi/acctl/alarms.lua \
		$(1)/usr/lib/lua/luci/model/cbi/acctl/alarms.lua
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/model/cbi/acctl/ap_list.lua \
		$(1)/usr/lib/lua/luci/model/cbi/acctl/ap_list.lua
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/model/cbi/acctl/firmware.lua \
		$(1)/usr/lib/lua/luci/model/cbi/acctl/firmware.lua
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/model/cbi/acctl/general.lua \
		$(1)/usr/lib/lua/luci/model/cbi/acctl/general.lua
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/model/cbi/acctl/groups.lua \
		$(1)/usr/lib/lua/luci/model/cbi/acctl/groups.lua
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/model/cbi/acctl/system.lua \
		$(1)/usr/lib/lua/luci/model/cbi/acctl/system.lua
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/model/cbi/acctl/templates.lua \
		$(1)/usr/lib/lua/luci/model/cbi/acctl/templates.lua

	$(INSTALL_DIR) $(1)/usr/lib/lua/luci/view/acctl
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/alarm_level_badge.htm \
		$(1)/usr/lib/lua/luci/view/acctl/alarm_level_badge.htm
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/ap_band.htm \
		$(1)/usr/lib/lua/luci/view/acctl/ap_band.htm
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/ap_info.htm \
		$(1)/usr/lib/lua/luci/view/acctl/ap_info.htm
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/ap_status.htm \
		$(1)/usr/lib/lua/luci/view/acctl/ap_status.htm
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/ap_status_badge.htm \
		$(1)/usr/lib/lua/luci/view/acctl/ap_status_badge.htm
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/ap_status_info.htm \
		$(1)/usr/lib/lua/luci/view/acctl/ap_status_info.htm
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/ap_wifi.htm \
		$(1)/usr/lib/lua/luci/view/acctl/ap_wifi.htm
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/status_bar.htm \
		$(1)/usr/lib/lua/luci/view/acctl/status_bar.htm
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci/applications/luci-app-acctl/view/acctl/user_badge.htm \
		$(1)/usr/lib/lua/luci/view/acctl/user_badge.htm

	# Install LuCI files for OpenWrt 22+ (ucode)
	$(INSTALL_DIR) $(1)/usr/share/ucode/luci/controller
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci24/usr/share/ucode/luci/controller/acctl.js \
		$(1)/usr/share/ucode/luci/controller/acctl.js

	$(INSTALL_DIR) $(1)/usr/share/luci/views/acctl
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci24/usr/share/luci/views/acctl/*.ut \
		$(1)/usr/share/luci/views/acctl/

	$(INSTALL_DIR) $(1)/usr/share/rpcd/acl.d
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/luci24/usr/share/rpcd/acl.d/luci-app-acctl.json \
		$(1)/usr/share/rpcd/acl.d/luci-app-acctl.json
endef

$(eval $(call BuildPackage,luci-app-acctl))