#!/bin/sh /etc/rc.common
# acctl-ac init script for OpenWrt
# AC Controller Server - runs on central controller device

START=95
STOP=15
USE_PROCD=1

NAME=acctl-ac
PROG=/usr/bin/acser

append_bool() {
	local section="$1"
	local option="$2"
	local value="$3"
	local default="$4"
	local enabled

	config_get_bool enabled "$section" "$option" "$default"
	[ "$enabled" = "1" ] && echo "$value"
}

append_string() {
	local section="$1"
	local option="$2"
	local value="$3"
	local default="$4"
	local pass="$5"

	config_get value "$section" "$option" "$default"
	[ -n "$value" ] && echo "$value"
}

start_service() {
	config_load 'acctl-ac'

	local enabled
	config_get_bool enabled 'global' 'enabled' '0'

	[ "$enabled" != "1" ] && {
		echo "acctl-ac is disabled"
		return 1
	}

	procd_open_instance
	procd_set_param command "$PROG"

	config_get_bool debug 'global' 'debug' '0'
	[ "$debug" = "1" ] && procd_append_param command '-d'

	config_get name 'global' 'name' 'OpenWrt-AC'
	procd_append_param command -n "$name"

	config_get nic 'network' 'nic' 'br-lan'
	[ -n "$nic" ] && procd_append_param command -i "$nic"

	config_get port 'network' 'port' '5246'
	procd_append_param command -p "$port"

	config_get http_port 'network' 'http_port' '8080'
	procd_append_param command --http-port "$http_port"

	config_get password 'security' 'password' ''
	[ -n "$password" ] && procd_append_param command -s "$password"

	config_get_bool dtls 'security' 'dtls_enabled' '0'
	[ "$dtls" = "1" ] && procd_append_param command --dtls

	config_get ip_start 'resource' 'ip_start' '192.168.1.200'
	config_get ip_end 'resource' 'ip_end' '192.168.1.254'
	config_get ip_mask 'resource' 'ip_mask' '255.255.255.0'
	procd_append_param command --ip-pool "$ip_start,$ip_end,$ip_mask"

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

reload_service() {
	killall -HUP acser 2>/dev/null
}

stop_service() {
	killall acser 2>/dev/null
}
