#!/bin/sh /etc/rc.common
# acctl-ap init script for OpenWrt
# AP Client - runs on managed Access Points

START=96
STOP=15
USE_PROCD=1

NAME=acctl-ap
PROG=/usr/bin/apctl

start_service() {
	config_load 'acctl-ap'

	local enabled
	config_get_bool enabled 'global' 'enabled' '0'

	[ "$enabled" != "1" ] && {
		echo "acctl-ap is disabled"
		return 1
	}

	procd_open_instance
	procd_set_param command "$PROG"

	config_get_bool debug 'global' 'debug' '0'
	[ "$debug" = "1" ] && procd_append_param command '-d'

	config_get ac_ip 'global' 'ac_ip' '192.168.1.1'
	procd_append_param command -a "$ac_ip"

	config_get ac_port 'global' 'ac_port' '5246'
	procd_append_param command -p "$ac_port"

	config_get nic 'device' 'nic' 'br-lan'
	[ -n "$nic" ] && procd_append_param command -i "$nic"

	config_get heartbeat 'global' 'heartbeat_interval' '30'
	procd_append_param command -h "$heartbeat"

	config_get password 'security' 'password' ''
	[ -n "$password" ] && procd_append_param command -s "$password"

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

reload_service() {
	killall -HUP apctl 2>/dev/null
}

stop_service() {
	killall apctl 2>/dev/null
}
