#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 /usr/lib/acctl/ac_server.py
    procd_set_param user root
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3 5
    procd_set_param file /etc/config/acctl-py
    procd_close_instance
}

stop_service() {
    killall -TERM python3 2>/dev/null || true
}

reload_service() {
    stop
    start
}